// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package edu.cmu.cs.mse.apidesigna3.grpc.user;

public final class UserOuterClass {

	private static final com.google.protobuf.Descriptors.Descriptor
		internal_static_edu_cmu_cs_mse_apidesigna3_model_user_User_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internal_static_edu_cmu_cs_mse_apidesigna3_model_user_User_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.FileDescriptor
		descriptor;

	static {
		String[] descriptorData = {
			"\n\nuser.proto\022%edu.cmu.cs.mse.apidesigna3" +
				".model.user\"\027\n\004User\022\017\n\007user_id\030\001 \001(\t2\r\n\013" +
				"UserServiceb\006proto3"
		};
		descriptor = com.google.protobuf.Descriptors.FileDescriptor
			.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[]{
				});
		internal_static_edu_cmu_cs_mse_apidesigna3_model_user_User_descriptor =
			getDescriptor().getMessageTypes().get(0);
		internal_static_edu_cmu_cs_mse_apidesigna3_model_user_User_fieldAccessorTable = new
			com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
			internal_static_edu_cmu_cs_mse_apidesigna3_model_user_User_descriptor,
			new String[]{"UserId",});
	}

	private UserOuterClass() {
	}

	public static void registerAllExtensions(
		com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
		com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
			(com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	public interface UserOrBuilder extends
		// @@protoc_insertion_point(interface_extends:edu.cmu.cs.mse.apidesigna3.model.user.User)
		com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string user_id = 1;</code>
		 *
		 * @return The userId.
		 */
		String getUserId();

		/**
		 * <code>string user_id = 1;</code>
		 *
		 * @return The bytes for userId.
		 */
		com.google.protobuf.ByteString
		getUserIdBytes();
	}

	/**
	 * Protobuf type {@code edu.cmu.cs.mse.apidesigna3.model.user.User}
	 */
	public static final class User extends
		com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:edu.cmu.cs.mse.apidesigna3.model.user.User)
		UserOrBuilder {

		public static final int USER_ID_FIELD_NUMBER = 1;
		private static final long serialVersionUID = 0L;
		// @@protoc_insertion_point(class_scope:edu.cmu.cs.mse.apidesigna3.model.user.User)
		private static final User DEFAULT_INSTANCE;
		private static final com.google.protobuf.Parser<User>
			PARSER = new com.google.protobuf.AbstractParser<User>() {
			@Override
			public User parsePartialFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
				Builder builder = newBuilder();
				try {
					builder.mergeFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(builder.buildPartial());
				} catch (com.google.protobuf.UninitializedMessageException e) {
					throw e.asInvalidProtocolBufferException()
						.setUnfinishedMessage(builder.buildPartial());
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e)
						.setUnfinishedMessage(builder.buildPartial());
				}
				return builder.buildPartial();
			}
		};

		static {
			DEFAULT_INSTANCE = new User();
		}

		@SuppressWarnings("serial")
		private volatile Object userId_ = "";
		private byte memoizedIsInitialized = -1;

		// Use User.newBuilder() to construct.
		private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private User() {
			userId_ = "";
		}

		public static com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return UserOuterClass.internal_static_edu_cmu_cs_mse_apidesigna3_model_user_User_descriptor;
		}

		public static User parseFrom(
			java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static User parseFrom(
			java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static User parseFrom(
			com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static User parseFrom(
			com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static User parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static User parseFrom(
			byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static User parseFrom(java.io.InputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
		}

		public static User parseFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static User parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input);
		}

		public static User parseDelimitedFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static User parseFrom(
			com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
		}

		public static User parseFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(User prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public static User getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		public static com.google.protobuf.Parser<User> parser() {
			return PARSER;
		}

		@Override
		@SuppressWarnings({"unused"})
		protected Object newInstance(
			UnusedPrivateParameter unused) {
			return new User();
		}

		@Override
		protected FieldAccessorTable
		internalGetFieldAccessorTable() {
			return UserOuterClass.internal_static_edu_cmu_cs_mse_apidesigna3_model_user_User_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
					User.class, Builder.class);
		}

		/**
		 * <code>string user_id = 1;</code>
		 *
		 * @return The userId.
		 */
		@Override
		public String getUserId() {
			Object ref = userId_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs =
					(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				userId_ = s;
				return s;
			}
		}

		/**
		 * <code>string user_id = 1;</code>
		 *
		 * @return The bytes for userId.
		 */
		@Override
		public com.google.protobuf.ByteString
		getUserIdBytes() {
			Object ref = userId_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
					com.google.protobuf.ByteString.copyFromUtf8(
						(String) ref);
				userId_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		@Override
		public boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) {
				return true;
			}
			if (isInitialized == 0) {
				return false;
			}

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
			throws java.io.IOException {
			if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
			}
			getUnknownFields().writeTo(output);
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@Override
		public boolean equals(final Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof User other)) {
				return super.equals(obj);
			}

			if (!getUserId()
				.equals(other.getUserId())) {
				return false;
			}
			return getUnknownFields().equals(other.getUnknownFields());
		}

		@Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + USER_ID_FIELD_NUMBER;
			hash = (53 * hash) + getUserId().hashCode();
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
				? new Builder() : new Builder().mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(
			BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		@Override
		public com.google.protobuf.Parser<User> getParserForType() {
			return PARSER;
		}

		@Override
		public User getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

		/**
		 * Protobuf type {@code edu.cmu.cs.mse.apidesigna3.model.user.User}
		 */
		public static final class Builder extends
			com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:edu.cmu.cs.mse.apidesigna3.model.user.User)
			UserOrBuilder {

			private int bitField0_;
			private Object userId_ = "";

			// Construct using edu.cmu.cs.mse.apidesigna3.model.user.UserOuterClass.User.newBuilder()
			private Builder() {

			}

			private Builder(
				BuilderParent parent) {
				super(parent);

			}

			public static com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return UserOuterClass.internal_static_edu_cmu_cs_mse_apidesigna3_model_user_User_descriptor;
			}

			@Override
			protected FieldAccessorTable
			internalGetFieldAccessorTable() {
				return UserOuterClass.internal_static_edu_cmu_cs_mse_apidesigna3_model_user_User_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
						User.class, Builder.class);
			}

			@Override
			public Builder clear() {
				super.clear();
				bitField0_ = 0;
				userId_ = "";
				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return UserOuterClass.internal_static_edu_cmu_cs_mse_apidesigna3_model_user_User_descriptor;
			}

			@Override
			public User getDefaultInstanceForType() {
				return User.getDefaultInstance();
			}

			@Override
			public User build() {
				User result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public User buildPartial() {
				User result = new User(this);
				if (bitField0_ != 0) {
					buildPartial0(result);
				}
				onBuilt();
				return result;
			}

			private void buildPartial0(User result) {
				int from_bitField0_ = bitField0_;
				if (((from_bitField0_ & 0x00000001) != 0)) {
					result.userId_ = userId_;
				}
			}

			@Override
			public Builder clone() {
				return super.clone();
			}

			@Override
			public Builder setField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				Object value) {
				return super.setField(field, value);
			}

			@Override
			public Builder clearField(
				com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@Override
			public Builder clearOneof(
				com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				int index, Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				Object value) {
				return super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof User) {
					return mergeFrom((User) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(User other) {
				if (other == User.getDefaultInstance()) {
					return this;
				}
				if (!other.getUserId().isEmpty()) {
					userId_ = other.userId_;
					bitField0_ |= 0x00000001;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				onChanged();
				return this;
			}

			@Override
			public boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
				if (extensionRegistry == null) {
					throw new NullPointerException();
				}
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
							case 0:
								done = true;
								break;
							case 10: {
								userId_ = input.readStringRequireUtf8();
								bitField0_ |= 0x00000001;
								break;
							} // case 10
							default: {
								if (!super.parseUnknownField(input, extensionRegistry, tag)) {
									done = true; // was an endgroup tag
								}
								break;
							} // default:
						} // switch (tag)
					} // while (!done)
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.unwrapIOException();
				} finally {
					onChanged();
				} // finally
				return this;
			}

			/**
			 * <code>string user_id = 1;</code>
			 *
			 * @return The userId.
			 */
			public String getUserId() {
				Object ref = userId_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					userId_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			/**
			 * <code>string user_id = 1;</code>
			 *
			 * @param value The userId to set.
			 * @return This builder for chaining.
			 */
			public Builder setUserId(
				String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				userId_ = value;
				bitField0_ |= 0x00000001;
				onChanged();
				return this;
			}

			/**
			 * <code>string user_id = 1;</code>
			 *
			 * @return The bytes for userId.
			 */
			public com.google.protobuf.ByteString
			getUserIdBytes() {
				Object ref = userId_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
							(String) ref);
					userId_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string user_id = 1;</code>
			 *
			 * @param value The bytes for userId to set.
			 * @return This builder for chaining.
			 */
			public Builder setUserIdBytes(
				com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);
				userId_ = value;
				bitField0_ |= 0x00000001;
				onChanged();
				return this;
			}

			/**
			 * <code>string user_id = 1;</code>
			 *
			 * @return This builder for chaining.
			 */
			public Builder clearUserId() {
				userId_ = getDefaultInstance().getUserId();
				bitField0_ = (bitField0_ & ~0x00000001);
				onChanged();
				return this;
			}

			@Override
			public Builder setUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@Override
			public Builder mergeUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:edu.cmu.cs.mse.apidesigna3.model.user.User)
		}

	}

	// @@protoc_insertion_point(outer_class_scope)
}
